language: d
sudo: false

d:
  - dmd
  - ldc
  - dmd-2.069.0
  - dmd-2.070.2
  - dmd-2.071.2
  - dmd-2.072.2
  - dmd-2.073.2
  - dmd-2.074.0
  - ldc-1.0.0
  - ldc-1.1.1

script:
  - dub test

notifications:
  email: false
